<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Jellyfin.Plugin.JellySync</AssemblyName>
    <RootNamespace>Jellyfin.Plugin.JellySync</RootNamespace>
    <Version>0.1.6.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="10.11.11" ExcludeAssets="runtime" />
    <PackageReference Include="Jellyfin.Model" Version="10.11.11" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <EmbeddedResource Include="Configuration/configPage.html" />
    <EmbeddedResource Include="Configuration/configPage.js" />
  </ItemGroup>
</Project>
